# Generated by Django 2.2 on 2022-06-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='discount_price',
            new_name='dollar_price',
        ),
    ]
