# Generated by Django 2.2 on 2022-06-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220601_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='book_title',
            new_name='name',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateTimeField()),
                ('ordered', models.BooleanField()),
                ('ordered_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('datetime_ofpayment', models.DateTimeField(auto_now_add=True)),
                ('oder_delivered', models.BooleanField(default=False)),
                ('oder_received', models.BooleanField(default=False)),
                ('flutewave_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('flutewave_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('flutewave_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('items', models.ManyToManyField(to='index.OrderItem')),
            ],
        ),
    ]
