# Generated by Django 2.2 on 2022-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_publication_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1, max_length=200)),
                ('state', models.CharField(default='enter state', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
