# Generated by Django 2.2 on 2022-06-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220603_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(default='enter address', max_length=150)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='index.Publication')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
