# Generated by Django 2.2 on 2022-06-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220603_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='shipping_address',
            name='lastname',
        ),
    ]
