# Generated by Django 2.2 on 2022-06-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20220603_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
