# Generated by Django 2.2 on 2022-06-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20220603_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shipping_address',
            new_name='ShippingAddress',
        ),
    ]
