# Generated by Django 2.2 on 2022-06-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20220603_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullname',
            new_name='name',
        ),
    ]
