# Generated by Django 2.2 on 2022-06-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20220605_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultion',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
